include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable all style-preference and optimization suggestion rules
    curly_braces_in_flow_control_structures: false
    sort_child_properties_last: false
    unnecessary_brace_in_string_interps: false
    empty_catches: false
    prefer_conditional_assignment: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    prefer_interpolation_to_compose_strings: false
    
analyzer:
  errors:
    # Ignore deprecation warnings - our uses are intentional
    deprecated_member_use: ignore
    # Ignore package dependencies - cross_file is transitive
    depend_on_referenced_packages: ignore
    # Ignore unnecessary imports - handled separately
    unnecessary_import: ignore
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
